export const ADD_TODO_SUCCESS = 'ADD_TODO_SUCCESS';
export const ADD_TODO_REQUESTED = 'ADD_TODO_REQUESTED';
export const COMPLETE_TODO_SUCCESS = 'COMPLETE_TODO_SUCCESS';
export const COMPLETE_TODO_REQUESTED = 'COMPLETE_TODO_REQUESTED';
export const DELETE_ALL_TODO_SUCCESS = 'DELETE_ALL_TODO_SUCCESS';
export const DELETE_ALL_TODO_REQUESTED = 'DELETE_ALL_TODO_REQUESTED';
export const DELETE_TODO_SUCCESS = 'DELETE_TODO_SUCCESS';
export const DELETE_TODO_REQUESTED = 'DELETE_TODO_REQUESTED';
export const FILTER_TODO_SUCCESS = 'FILTER_TODO_SUCCESS';
export const FILTER_TODO_REQUESTED = 'FILTER_TODO_REQUESTED';

export const REMOVE_TOAST = 'REMOVE_TOAST';

export const ADD_TODO_ERROR = 'ADD_TODO_ERROR';

export const SET_IS_LOADING = 'SET_IS_LOADING';
